/**
 * A dictionary of countries keyed by their ISO 3166-1 codes.
 *
 * Taken from the slim-2 directory of https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes
 * which contains:
 *
 * "the result of merging data from two sources, the Wikipedia ISO 3166-1 article for alpha and numeric
 * country codes, and the UN M49 Standard country or area codes for statistical use data for countries'
 * regional, and sub-regional codes. In addition to countries, it includes dependent territories."
 */
export const countries = {
  AF: {
    name: "Afghanistan",
    alpha: "AF",
    code: "004",
    region: "Asia",
    subRegion: "Southern Asia",
    intermediateRegion: "",
  },
  AX: {
    name: "Åland Islands",
    alpha: "AX",
    code: "248",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: "",
  },
  AL: {
    name: "Albania",
    alpha: "AL",
    code: "008",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: "",
  },
  DZ: {
    name: "Algeria",
    alpha: "DZ",
    code: "012",
    region: "Africa",
    subRegion: "Northern Africa",
    intermediateRegion: "",
  },
  AS: {
    name: "American Samoa",
    alpha: "AS",
    code: "016",
    region: "Oceania",
    subRegion: "Polynesia",
    intermediateRegion: "",
  },
  AD: {
    name: "Andorra",
    alpha: "AD",
    code: "020",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: "",
  },
  AO: {
    name: "Angola",
    alpha: "AO",
    code: "024",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Middle Africa",
  },
  AI: {
    name: "Anguilla",
    alpha: "AI",
    code: "660",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  AQ: {
    name: "Antarctica",
    alpha: "AQ",
    code: "010",
    region: "",
    subRegion: "",
    intermediateRegion: "",
  },
  AG: {
    name: "Antigua and Barbuda",
    alpha: "AG",
    code: "028",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  AR: {
    name: "Argentina",
    alpha: "AR",
    code: "032",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  AM: {
    name: "Armenia",
    alpha: "AM",
    code: "051",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: "",
  },
  AW: {
    name: "Aruba",
    alpha: "AW",
    code: "533",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  AU: {
    name: "Australia",
    alpha: "AU",
    code: "036",
    region: "Oceania",
    subRegion: "Australia and New Zealand",
    intermediateRegion: "",
  },
  AT: {
    name: "Austria",
    alpha: "AT",
    code: "040",
    region: "Europe",
    subRegion: "Western Europe",
    intermediateRegion: "",
  },
  AZ: {
    name: "Azerbaijan",
    alpha: "AZ",
    code: "031",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: "",
  },
  BS: {
    name: "Bahamas",
    alpha: "BS",
    code: "044",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  BH: {
    name: "Bahrain",
    alpha: "BH",
    code: "048",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: "",
  },
  BD: {
    name: "Bangladesh",
    alpha: "BD",
    code: "050",
    region: "Asia",
    subRegion: "Southern Asia",
    intermediateRegion: "",
  },
  BB: {
    name: "Barbados",
    alpha: "BB",
    code: "052",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  BY: {
    name: "Belarus",
    alpha: "BY",
    code: "112",
    region: "Europe",
    subRegion: "Eastern Europe",
    intermediateRegion: "",
  },
  BE: {
    name: "Belgium",
    alpha: "BE",
    code: "056",
    region: "Europe",
    subRegion: "Western Europe",
    intermediateRegion: "",
  },
  BZ: {
    name: "Belize",
    alpha: "BZ",
    code: "084",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Central America",
  },
  BJ: {
    name: "Benin",
    alpha: "BJ",
    code: "204",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  BM: {
    name: "Bermuda",
    alpha: "BM",
    code: "060",
    region: "Americas",
    subRegion: "Northern America",
    intermediateRegion: "",
  },
  BT: {
    name: "Bhutan",
    alpha: "BT",
    code: "064",
    region: "Asia",
    subRegion: "Southern Asia",
    intermediateRegion: "",
  },
  BO: {
    name: "Bolivia, Plurinational State of",
    alpha: "BO",
    code: "068",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  BQ: {
    name: "Bonaire, Sint Eustatius and Saba",
    alpha: "BQ",
    code: "535",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  BA: {
    name: "Bosnia and Herzegovina",
    alpha: "BA",
    code: "070",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: "",
  },
  BW: {
    name: "Botswana",
    alpha: "BW",
    code: "072",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Southern Africa",
  },
  BV: {
    name: "Bouvet Island",
    alpha: "BV",
    code: "074",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  BR: {
    name: "Brazil",
    alpha: "BR",
    code: "076",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  IO: {
    name: "British Indian Ocean Territory",
    alpha: "IO",
    code: "086",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  BN: {
    name: "Brunei Darussalam",
    alpha: "BN",
    code: "096",
    region: "Asia",
    subRegion: "South-eastern Asia",
    intermediateRegion: "",
  },
  BG: {
    name: "Bulgaria",
    alpha: "BG",
    code: "100",
    region: "Europe",
    subRegion: "Eastern Europe",
    intermediateRegion: "",
  },
  BF: {
    name: "Burkina Faso",
    alpha: "BF",
    code: "854",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  BI: {
    name: "Burundi",
    alpha: "BI",
    code: "108",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  CV: {
    name: "Cabo Verde",
    alpha: "CV",
    code: "132",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  KH: {
    name: "Cambodia",
    alpha: "KH",
    code: "116",
    region: "Asia",
    subRegion: "South-eastern Asia",
    intermediateRegion: "",
  },
  CM: {
    name: "Cameroon",
    alpha: "CM",
    code: "120",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Middle Africa",
  },
  CA: {
    name: "Canada",
    alpha: "CA",
    code: "124",
    region: "Americas",
    subRegion: "Northern America",
    intermediateRegion: "",
  },
  KY: {
    name: "Cayman Islands",
    alpha: "KY",
    code: "136",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  CF: {
    name: "Central African Republic",
    alpha: "CF",
    code: "140",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Middle Africa",
  },
  TD: {
    name: "Chad",
    alpha: "TD",
    code: "148",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Middle Africa",
  },
  CL: {
    name: "Chile",
    alpha: "CL",
    code: "152",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  CN: {
    name: "China",
    alpha: "CN",
    code: "156",
    region: "Asia",
    subRegion: "Eastern Asia",
    intermediateRegion: "",
  },
  CX: {
    name: "Christmas Island",
    alpha: "CX",
    code: "162",
    region: "Oceania",
    subRegion: "Australia and New Zealand",
    intermediateRegion: "",
  },
  CC: {
    name: "Cocos (Keeling) Islands",
    alpha: "CC",
    code: "166",
    region: "Oceania",
    subRegion: "Australia and New Zealand",
    intermediateRegion: "",
  },
  CO: {
    name: "Colombia",
    alpha: "CO",
    code: "170",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  KM: {
    name: "Comoros",
    alpha: "KM",
    code: "174",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  CG: {
    name: "Congo",
    alpha: "CG",
    code: "178",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Middle Africa",
  },
  CD: {
    name: "Congo, Democratic Republic of the",
    alpha: "CD",
    code: "180",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Middle Africa",
  },
  CK: {
    name: "Cook Islands",
    alpha: "CK",
    code: "184",
    region: "Oceania",
    subRegion: "Polynesia",
    intermediateRegion: "",
  },
  CR: {
    name: "Costa Rica",
    alpha: "CR",
    code: "188",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Central America",
  },
  CI: {
    name: "Côte d'Ivoire",
    alpha: "CI",
    code: "384",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  HR: {
    name: "Croatia",
    alpha: "HR",
    code: "191",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: "",
  },
  CU: {
    name: "Cuba",
    alpha: "CU",
    code: "192",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  CW: {
    name: "Curaçao",
    alpha: "CW",
    code: "531",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  CY: {
    name: "Cyprus",
    alpha: "CY",
    code: "196",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: "",
  },
  CZ: {
    name: "Czechia",
    alpha: "CZ",
    code: "203",
    region: "Europe",
    subRegion: "Eastern Europe",
    intermediateRegion: "",
  },
  DK: {
    name: "Denmark",
    alpha: "DK",
    code: "208",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: "",
  },
  DJ: {
    name: "Djibouti",
    alpha: "DJ",
    code: "262",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  DM: {
    name: "Dominica",
    alpha: "DM",
    code: "212",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  DO: {
    name: "Dominican Republic",
    alpha: "DO",
    code: "214",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  EC: {
    name: "Ecuador",
    alpha: "EC",
    code: "218",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  EG: {
    name: "Egypt",
    alpha: "EG",
    code: "818",
    region: "Africa",
    subRegion: "Northern Africa",
    intermediateRegion: "",
  },
  SV: {
    name: "El Salvador",
    alpha: "SV",
    code: "222",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Central America",
  },
  GQ: {
    name: "Equatorial Guinea",
    alpha: "GQ",
    code: "226",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Middle Africa",
  },
  ER: {
    name: "Eritrea",
    alpha: "ER",
    code: "232",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  EE: {
    name: "Estonia",
    alpha: "EE",
    code: "233",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: "",
  },
  SZ: {
    name: "Eswatini",
    alpha: "SZ",
    code: "748",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Southern Africa",
  },
  ET: {
    name: "Ethiopia",
    alpha: "ET",
    code: "231",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  FK: {
    name: "Falkland Islands (Malvinas)",
    alpha: "FK",
    code: "238",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  FO: {
    name: "Faroe Islands",
    alpha: "FO",
    code: "234",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: "",
  },
  FJ: {
    name: "Fiji",
    alpha: "FJ",
    code: "242",
    region: "Oceania",
    subRegion: "Melanesia",
    intermediateRegion: "",
  },
  FI: {
    name: "Finland",
    alpha: "FI",
    code: "246",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: "",
  },
  FR: {
    name: "France",
    alpha: "FR",
    code: "250",
    region: "Europe",
    subRegion: "Western Europe",
    intermediateRegion: "",
  },
  GF: {
    name: "French Guiana",
    alpha: "GF",
    code: "254",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  PF: {
    name: "French Polynesia",
    alpha: "PF",
    code: "258",
    region: "Oceania",
    subRegion: "Polynesia",
    intermediateRegion: "",
  },
  TF: {
    name: "French Southern Territories",
    alpha: "TF",
    code: "260",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  GA: {
    name: "Gabon",
    alpha: "GA",
    code: "266",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Middle Africa",
  },
  GM: {
    name: "Gambia",
    alpha: "GM",
    code: "270",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  GE: {
    name: "Georgia",
    alpha: "GE",
    code: "268",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: "",
  },
  DE: {
    name: "Germany",
    alpha: "DE",
    code: "276",
    region: "Europe",
    subRegion: "Western Europe",
    intermediateRegion: "",
  },
  GH: {
    name: "Ghana",
    alpha: "GH",
    code: "288",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  GI: {
    name: "Gibraltar",
    alpha: "GI",
    code: "292",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: "",
  },
  GR: {
    name: "Greece",
    alpha: "GR",
    code: "300",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: "",
  },
  GL: {
    name: "Greenland",
    alpha: "GL",
    code: "304",
    region: "Americas",
    subRegion: "Northern America",
    intermediateRegion: "",
  },
  GD: {
    name: "Grenada",
    alpha: "GD",
    code: "308",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  GP: {
    name: "Guadeloupe",
    alpha: "GP",
    code: "312",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  GU: {
    name: "Guam",
    alpha: "GU",
    code: "316",
    region: "Oceania",
    subRegion: "Micronesia",
    intermediateRegion: "",
  },
  GT: {
    name: "Guatemala",
    alpha: "GT",
    code: "320",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Central America",
  },
  GG: {
    name: "Guernsey",
    alpha: "GG",
    code: "831",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: "",
  },
  GN: {
    name: "Guinea",
    alpha: "GN",
    code: "324",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  GW: {
    name: "Guinea-Bissau",
    alpha: "GW",
    code: "624",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  GY: {
    name: "Guyana",
    alpha: "GY",
    code: "328",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  HT: {
    name: "Haiti",
    alpha: "HT",
    code: "332",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  HM: {
    name: "Heard Island and McDonald Islands",
    alpha: "HM",
    code: "334",
    region: "Oceania",
    subRegion: "Australia and New Zealand",
    intermediateRegion: "",
  },
  VA: {
    name: "Holy See",
    alpha: "VA",
    code: "336",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: "",
  },
  HN: {
    name: "Honduras",
    alpha: "HN",
    code: "340",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Central America",
  },
  HK: {
    name: "Hong Kong",
    alpha: "HK",
    code: "344",
    region: "Asia",
    subRegion: "Eastern Asia",
    intermediateRegion: "",
  },
  HU: {
    name: "Hungary",
    alpha: "HU",
    code: "348",
    region: "Europe",
    subRegion: "Eastern Europe",
    intermediateRegion: "",
  },
  IS: {
    name: "Iceland",
    alpha: "IS",
    code: "352",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: "",
  },
  IN: {
    name: "India",
    alpha: "IN",
    code: "356",
    region: "Asia",
    subRegion: "Southern Asia",
    intermediateRegion: "",
  },
  ID: {
    name: "Indonesia",
    alpha: "ID",
    code: "360",
    region: "Asia",
    subRegion: "South-eastern Asia",
    intermediateRegion: "",
  },
  IR: {
    name: "Iran, Islamic Republic of",
    alpha: "IR",
    code: "364",
    region: "Asia",
    subRegion: "Southern Asia",
    intermediateRegion: "",
  },
  IQ: {
    name: "Iraq",
    alpha: "IQ",
    code: "368",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: "",
  },
  IE: {
    name: "Ireland",
    alpha: "IE",
    code: "372",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: "",
  },
  IM: {
    name: "Isle of Man",
    alpha: "IM",
    code: "833",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: "",
  },
  IL: {
    name: "Israel",
    alpha: "IL",
    code: "376",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: "",
  },
  IT: {
    name: "Italy",
    alpha: "IT",
    code: "380",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: "",
  },
  JM: {
    name: "Jamaica",
    alpha: "JM",
    code: "388",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  JP: {
    name: "Japan",
    alpha: "JP",
    code: "392",
    region: "Asia",
    subRegion: "Eastern Asia",
    intermediateRegion: "",
  },
  JE: {
    name: "Jersey",
    alpha: "JE",
    code: "832",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: "",
  },
  JO: {
    name: "Jordan",
    alpha: "JO",
    code: "400",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: "",
  },
  KZ: {
    name: "Kazakhstan",
    alpha: "KZ",
    code: "398",
    region: "Asia",
    subRegion: "Central Asia",
    intermediateRegion: "",
  },
  KE: {
    name: "Kenya",
    alpha: "KE",
    code: "404",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  KI: {
    name: "Kiribati",
    alpha: "KI",
    code: "296",
    region: "Oceania",
    subRegion: "Micronesia",
    intermediateRegion: "",
  },
  KP: {
    name: "Korea, Democratic People's Republic of",
    alpha: "KP",
    code: "408",
    region: "Asia",
    subRegion: "Eastern Asia",
    intermediateRegion: "",
  },
  KR: {
    name: "Korea, Republic of",
    alpha: "KR",
    code: "410",
    region: "Asia",
    subRegion: "Eastern Asia",
    intermediateRegion: "",
  },
  KW: {
    name: "Kuwait",
    alpha: "KW",
    code: "414",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: "",
  },
  KG: {
    name: "Kyrgyzstan",
    alpha: "KG",
    code: "417",
    region: "Asia",
    subRegion: "Central Asia",
    intermediateRegion: "",
  },
  LA: {
    name: "Lao People's Democratic Republic",
    alpha: "LA",
    code: "418",
    region: "Asia",
    subRegion: "South-eastern Asia",
    intermediateRegion: "",
  },
  LV: {
    name: "Latvia",
    alpha: "LV",
    code: "428",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: "",
  },
  LB: {
    name: "Lebanon",
    alpha: "LB",
    code: "422",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: "",
  },
  LS: {
    name: "Lesotho",
    alpha: "LS",
    code: "426",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Southern Africa",
  },
  LR: {
    name: "Liberia",
    alpha: "LR",
    code: "430",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  LY: {
    name: "Libya",
    alpha: "LY",
    code: "434",
    region: "Africa",
    subRegion: "Northern Africa",
    intermediateRegion: "",
  },
  LI: {
    name: "Liechtenstein",
    alpha: "LI",
    code: "438",
    region: "Europe",
    subRegion: "Western Europe",
    intermediateRegion: "",
  },
  LT: {
    name: "Lithuania",
    alpha: "LT",
    code: "440",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: "",
  },
  LU: {
    name: "Luxembourg",
    alpha: "LU",
    code: "442",
    region: "Europe",
    subRegion: "Western Europe",
    intermediateRegion: "",
  },
  MO: {
    name: "Macao",
    alpha: "MO",
    code: "446",
    region: "Asia",
    subRegion: "Eastern Asia",
    intermediateRegion: "",
  },
  MG: {
    name: "Madagascar",
    alpha: "MG",
    code: "450",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  MW: {
    name: "Malawi",
    alpha: "MW",
    code: "454",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  MY: {
    name: "Malaysia",
    alpha: "MY",
    code: "458",
    region: "Asia",
    subRegion: "South-eastern Asia",
    intermediateRegion: "",
  },
  MV: {
    name: "Maldives",
    alpha: "MV",
    code: "462",
    region: "Asia",
    subRegion: "Southern Asia",
    intermediateRegion: "",
  },
  ML: {
    name: "Mali",
    alpha: "ML",
    code: "466",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  MT: {
    name: "Malta",
    alpha: "MT",
    code: "470",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: "",
  },
  MH: {
    name: "Marshall Islands",
    alpha: "MH",
    code: "584",
    region: "Oceania",
    subRegion: "Micronesia",
    intermediateRegion: "",
  },
  MQ: {
    name: "Martinique",
    alpha: "MQ",
    code: "474",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  MR: {
    name: "Mauritania",
    alpha: "MR",
    code: "478",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  MU: {
    name: "Mauritius",
    alpha: "MU",
    code: "480",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  YT: {
    name: "Mayotte",
    alpha: "YT",
    code: "175",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  MX: {
    name: "Mexico",
    alpha: "MX",
    code: "484",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Central America",
  },
  FM: {
    name: "Micronesia, Federated States of",
    alpha: "FM",
    code: "583",
    region: "Oceania",
    subRegion: "Micronesia",
    intermediateRegion: "",
  },
  MD: {
    name: "Moldova, Republic of",
    alpha: "MD",
    code: "498",
    region: "Europe",
    subRegion: "Eastern Europe",
    intermediateRegion: "",
  },
  MC: {
    name: "Monaco",
    alpha: "MC",
    code: "492",
    region: "Europe",
    subRegion: "Western Europe",
    intermediateRegion: "",
  },
  MN: {
    name: "Mongolia",
    alpha: "MN",
    code: "496",
    region: "Asia",
    subRegion: "Eastern Asia",
    intermediateRegion: "",
  },
  ME: {
    name: "Montenegro",
    alpha: "ME",
    code: "499",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: "",
  },
  MS: {
    name: "Montserrat",
    alpha: "MS",
    code: "500",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  MA: {
    name: "Morocco",
    alpha: "MA",
    code: "504",
    region: "Africa",
    subRegion: "Northern Africa",
    intermediateRegion: "",
  },
  MZ: {
    name: "Mozambique",
    alpha: "MZ",
    code: "508",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  MM: {
    name: "Myanmar",
    alpha: "MM",
    code: "104",
    region: "Asia",
    subRegion: "South-eastern Asia",
    intermediateRegion: "",
  },
  NA: {
    name: "Namibia",
    alpha: "NA",
    code: "516",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Southern Africa",
  },
  NR: {
    name: "Nauru",
    alpha: "NR",
    code: "520",
    region: "Oceania",
    subRegion: "Micronesia",
    intermediateRegion: "",
  },
  NP: {
    name: "Nepal",
    alpha: "NP",
    code: "524",
    region: "Asia",
    subRegion: "Southern Asia",
    intermediateRegion: "",
  },
  NL: {
    name: "Netherlands, Kingdom of the",
    alpha: "NL",
    code: "528",
    region: "Europe",
    subRegion: "Western Europe",
    intermediateRegion: "",
  },
  NC: {
    name: "New Caledonia",
    alpha: "NC",
    code: "540",
    region: "Oceania",
    subRegion: "Melanesia",
    intermediateRegion: "",
  },
  NZ: {
    name: "New Zealand",
    alpha: "NZ",
    code: "554",
    region: "Oceania",
    subRegion: "Australia and New Zealand",
    intermediateRegion: "",
  },
  NI: {
    name: "Nicaragua",
    alpha: "NI",
    code: "558",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Central America",
  },
  NE: {
    name: "Niger",
    alpha: "NE",
    code: "562",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  NG: {
    name: "Nigeria",
    alpha: "NG",
    code: "566",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  NU: {
    name: "Niue",
    alpha: "NU",
    code: "570",
    region: "Oceania",
    subRegion: "Polynesia",
    intermediateRegion: "",
  },
  NF: {
    name: "Norfolk Island",
    alpha: "NF",
    code: "574",
    region: "Oceania",
    subRegion: "Australia and New Zealand",
    intermediateRegion: "",
  },
  MK: {
    name: "North Macedonia",
    alpha: "MK",
    code: "807",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: "",
  },
  MP: {
    name: "Northern Mariana Islands",
    alpha: "MP",
    code: "580",
    region: "Oceania",
    subRegion: "Micronesia",
    intermediateRegion: "",
  },
  NO: {
    name: "Norway",
    alpha: "NO",
    code: "578",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: "",
  },
  OM: {
    name: "Oman",
    alpha: "OM",
    code: "512",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: "",
  },
  PK: {
    name: "Pakistan",
    alpha: "PK",
    code: "586",
    region: "Asia",
    subRegion: "Southern Asia",
    intermediateRegion: "",
  },
  PW: {
    name: "Palau",
    alpha: "PW",
    code: "585",
    region: "Oceania",
    subRegion: "Micronesia",
    intermediateRegion: "",
  },
  PS: {
    name: "Palestine, State of",
    alpha: "PS",
    code: "275",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: "",
  },
  PA: {
    name: "Panama",
    alpha: "PA",
    code: "591",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Central America",
  },
  PG: {
    name: "Papua New Guinea",
    alpha: "PG",
    code: "598",
    region: "Oceania",
    subRegion: "Melanesia",
    intermediateRegion: "",
  },
  PY: {
    name: "Paraguay",
    alpha: "PY",
    code: "600",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  PE: {
    name: "Peru",
    alpha: "PE",
    code: "604",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  PH: {
    name: "Philippines",
    alpha: "PH",
    code: "608",
    region: "Asia",
    subRegion: "South-eastern Asia",
    intermediateRegion: "",
  },
  PN: {
    name: "Pitcairn",
    alpha: "PN",
    code: "612",
    region: "Oceania",
    subRegion: "Polynesia",
    intermediateRegion: "",
  },
  PL: {
    name: "Poland",
    alpha: "PL",
    code: "616",
    region: "Europe",
    subRegion: "Eastern Europe",
    intermediateRegion: "",
  },
  PT: {
    name: "Portugal",
    alpha: "PT",
    code: "620",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: "",
  },
  PR: {
    name: "Puerto Rico",
    alpha: "PR",
    code: "630",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  QA: {
    name: "Qatar",
    alpha: "QA",
    code: "634",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: "",
  },
  RE: {
    name: "Réunion",
    alpha: "RE",
    code: "638",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  RO: {
    name: "Romania",
    alpha: "RO",
    code: "642",
    region: "Europe",
    subRegion: "Eastern Europe",
    intermediateRegion: "",
  },
  RU: {
    name: "Russian Federation",
    alpha: "RU",
    code: "643",
    region: "Europe",
    subRegion: "Eastern Europe",
    intermediateRegion: "",
  },
  RW: {
    name: "Rwanda",
    alpha: "RW",
    code: "646",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  BL: {
    name: "Saint Barthélemy",
    alpha: "BL",
    code: "652",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  SH: {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    alpha: "SH",
    code: "654",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  KN: {
    name: "Saint Kitts and Nevis",
    alpha: "KN",
    code: "659",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  LC: {
    name: "Saint Lucia",
    alpha: "LC",
    code: "662",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  MF: {
    name: "Saint Martin (French part)",
    alpha: "MF",
    code: "663",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  PM: {
    name: "Saint Pierre and Miquelon",
    alpha: "PM",
    code: "666",
    region: "Americas",
    subRegion: "Northern America",
    intermediateRegion: "",
  },
  VC: {
    name: "Saint Vincent and the Grenadines",
    alpha: "VC",
    code: "670",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  WS: {
    name: "Samoa",
    alpha: "WS",
    code: "882",
    region: "Oceania",
    subRegion: "Polynesia",
    intermediateRegion: "",
  },
  SM: {
    name: "San Marino",
    alpha: "SM",
    code: "674",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: "",
  },
  ST: {
    name: "Sao Tome and Principe",
    alpha: "ST",
    code: "678",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Middle Africa",
  },
  SA: {
    name: "Saudi Arabia",
    alpha: "SA",
    code: "682",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: "",
  },
  SN: {
    name: "Senegal",
    alpha: "SN",
    code: "686",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  RS: {
    name: "Serbia",
    alpha: "RS",
    code: "688",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: "",
  },
  SC: {
    name: "Seychelles",
    alpha: "SC",
    code: "690",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  SL: {
    name: "Sierra Leone",
    alpha: "SL",
    code: "694",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  SG: {
    name: "Singapore",
    alpha: "SG",
    code: "702",
    region: "Asia",
    subRegion: "South-eastern Asia",
    intermediateRegion: "",
  },
  SX: {
    name: "Sint Maarten (Dutch part)",
    alpha: "SX",
    code: "534",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  SK: {
    name: "Slovakia",
    alpha: "SK",
    code: "703",
    region: "Europe",
    subRegion: "Eastern Europe",
    intermediateRegion: "",
  },
  SI: {
    name: "Slovenia",
    alpha: "SI",
    code: "705",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: "",
  },
  SB: {
    name: "Solomon Islands",
    alpha: "SB",
    code: "090",
    region: "Oceania",
    subRegion: "Melanesia",
    intermediateRegion: "",
  },
  SO: {
    name: "Somalia",
    alpha: "SO",
    code: "706",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  ZA: {
    name: "South Africa",
    alpha: "ZA",
    code: "710",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Southern Africa",
  },
  GS: {
    name: "South Georgia and the South Sandwich Islands",
    alpha: "GS",
    code: "239",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  SS: {
    name: "South Sudan",
    alpha: "SS",
    code: "728",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  ES: {
    name: "Spain",
    alpha: "ES",
    code: "724",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: "",
  },
  LK: {
    name: "Sri Lanka",
    alpha: "LK",
    code: "144",
    region: "Asia",
    subRegion: "Southern Asia",
    intermediateRegion: "",
  },
  SD: {
    name: "Sudan",
    alpha: "SD",
    code: "729",
    region: "Africa",
    subRegion: "Northern Africa",
    intermediateRegion: "",
  },
  SR: {
    name: "Suriname",
    alpha: "SR",
    code: "740",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  SJ: {
    name: "Svalbard and Jan Mayen",
    alpha: "SJ",
    code: "744",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: "",
  },
  SE: {
    name: "Sweden",
    alpha: "SE",
    code: "752",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: "",
  },
  CH: {
    name: "Switzerland",
    alpha: "CH",
    code: "756",
    region: "Europe",
    subRegion: "Western Europe",
    intermediateRegion: "",
  },
  SY: {
    name: "Syrian Arab Republic",
    alpha: "SY",
    code: "760",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: "",
  },
  TW: {
    name: "Taiwan, Province of China",
    alpha: "TW",
    code: "158",
    region: null,
    subRegion: null,
    intermediateRegion: null,
  },
  TJ: {
    name: "Tajikistan",
    alpha: "TJ",
    code: "762",
    region: "Asia",
    subRegion: "Central Asia",
    intermediateRegion: "",
  },
  TZ: {
    name: "Tanzania, United Republic of",
    alpha: "TZ",
    code: "834",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  TH: {
    name: "Thailand",
    alpha: "TH",
    code: "764",
    region: "Asia",
    subRegion: "South-eastern Asia",
    intermediateRegion: "",
  },
  TL: {
    name: "Timor-Leste",
    alpha: "TL",
    code: "626",
    region: "Asia",
    subRegion: "South-eastern Asia",
    intermediateRegion: "",
  },
  TG: {
    name: "Togo",
    alpha: "TG",
    code: "768",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  TK: {
    name: "Tokelau",
    alpha: "TK",
    code: "772",
    region: "Oceania",
    subRegion: "Polynesia",
    intermediateRegion: "",
  },
  TO: {
    name: "Tonga",
    alpha: "TO",
    code: "776",
    region: "Oceania",
    subRegion: "Polynesia",
    intermediateRegion: "",
  },
  TT: {
    name: "Trinidad and Tobago",
    alpha: "TT",
    code: "780",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  TN: {
    name: "Tunisia",
    alpha: "TN",
    code: "788",
    region: "Africa",
    subRegion: "Northern Africa",
    intermediateRegion: "",
  },
  TR: {
    name: "Türkiye",
    alpha: "TR",
    code: "792",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: "",
  },
  TM: {
    name: "Turkmenistan",
    alpha: "TM",
    code: "795",
    region: "Asia",
    subRegion: "Central Asia",
    intermediateRegion: "",
  },
  TC: {
    name: "Turks and Caicos Islands",
    alpha: "TC",
    code: "796",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  TV: {
    name: "Tuvalu",
    alpha: "TV",
    code: "798",
    region: "Oceania",
    subRegion: "Polynesia",
    intermediateRegion: "",
  },
  UG: {
    name: "Uganda",
    alpha: "UG",
    code: "800",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  UA: {
    name: "Ukraine",
    alpha: "UA",
    code: "804",
    region: "Europe",
    subRegion: "Eastern Europe",
    intermediateRegion: "",
  },
  AE: {
    name: "United Arab Emirates",
    alpha: "AE",
    code: "784",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: "",
  },
  GB: {
    name: "United Kingdom of Great Britain and Northern Ireland",
    alpha: "GB",
    code: "826",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: "",
  },
  US: {
    name: "United States of America",
    alpha: "US",
    code: "840",
    region: "Americas",
    subRegion: "Northern America",
    intermediateRegion: "",
  },
  UM: {
    name: "United States Minor Outlying Islands",
    alpha: "UM",
    code: "581",
    region: "Oceania",
    subRegion: "Micronesia",
    intermediateRegion: "",
  },
  UY: {
    name: "Uruguay",
    alpha: "UY",
    code: "858",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  UZ: {
    name: "Uzbekistan",
    alpha: "UZ",
    code: "860",
    region: "Asia",
    subRegion: "Central Asia",
    intermediateRegion: "",
  },
  VU: {
    name: "Vanuatu",
    alpha: "VU",
    code: "548",
    region: "Oceania",
    subRegion: "Melanesia",
    intermediateRegion: "",
  },
  VE: {
    name: "Venezuela, Bolivarian Republic of",
    alpha: "VE",
    code: "862",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  VN: {
    name: "Viet Nam",
    alpha: "VN",
    code: "704",
    region: "Asia",
    subRegion: "South-eastern Asia",
    intermediateRegion: "",
  },
  VG: {
    name: "Virgin Islands (British)",
    alpha: "VG",
    code: "092",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  VI: {
    name: "Virgin Islands (U.S.)",
    alpha: "VI",
    code: "850",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  WF: {
    name: "Wallis and Futuna",
    alpha: "WF",
    code: "876",
    region: "Oceania",
    subRegion: "Polynesia",
    intermediateRegion: "",
  },
  EH: {
    name: "Western Sahara",
    alpha: "EH",
    code: "732",
    region: "Africa",
    subRegion: "Northern Africa",
    intermediateRegion: "",
  },
  YE: {
    name: "Yemen",
    alpha: "YE",
    code: "887",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: "",
  },
  ZM: {
    name: "Zambia",
    alpha: "ZM",
    code: "894",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  ZW: {
    name: "Zimbabwe",
    alpha: "ZW",
    code: "716",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
};

/**
 * A set containing the 50 countries with the most internet users.
 *
 * Taken from https://en.wikipedia.org/wiki/List_of_countries_by_number_of_Internet_users which is
 * based off of estimates by the ITU.
 */
export const top50 = new Set([
  countries.CN,
  countries.IN,
  countries.US,
  countries.ID,
  countries.BR,
  countries.RU,
  countries.JP,
  countries.MX,
  countries.PH,
  countries.NG,
  countries.VN,
  countries.EG,
  countries.DE,
  countries.BD,
  countries.TR,
  countries.IR,
  countries.PK,
  countries.GB,
  countries.TH,
  countries.FR,
  countries.IT,
  countries.KR,
  countries.ZA,
  countries.ES,
  countries.AR,
  countries.CO,
  countries.SA,
  countries.CA,
  countries.DZ,
  countries.CD,
  countries.IQ,
  countries.PL,
  countries.MA,
  countries.MY,
  countries.MM,
  countries.UZ,
  countries.UA,
  countries.PE,
  countries.AU,
  countries.GH,
  countries.TW,
  countries.KE,
  countries.ET,
  countries.TZ,
  countries.VE,
  countries.KZ,
  countries.CL,
  countries.NP,
  countries.NL,
  countries.AO,
]);

/**
 * A set containing the country codes for the 50 countries with the most internet users.
 */
export const top50Codes = new Set([...top50].map((c) => c.alpha));
