name: Deploy the CDK stack
on:
  push:
    branches:
      - main

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npx lerna run build

      - name: Install LLRT test runner
        run: npx lerna run install-llrt-test-runner-linux --scope=lambda

      - name: Run tests
        run: npx lerna run test

      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'TinyMu-prod'
          cdk_args: '--require-approval never'
          working_dir: './packages/infra/'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-west-2'
